---
title: "Datos de felinos de CR"
author: "Walter Varela Nvarro"
date: '2022-06-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparativos  


``` {r}
library(dplyr)
library(sf)
library(ggplot2)
library(plotly)
library(DT)
library(leaflet)
```

```{r}
felinos <-
  st_read(
    "C:/Users/gf0604-1/prsctics-gdsl/clase 6 de junio (tema 13)/felinos/felinos.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"  
    ),
    quiet = TRUE
  )  
```

# Tabla  

``` {r tabla}
felinos %>%
  select(species,
         eventDate,
         stateProvince,
         locality,
         decimalLongitude,
         decimalLatitude) %>%
  st_drop_geometry() %>%
  datatable(
    colnames = c(
      "Especie",
      "Fecha",
      "Provincia",
      "Localidad",
      "Longitud",
      "Latitud"
    ),
      options = list(
        pageLength = 5,
        language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
      )
    )
```
# Gráfico
```{r grafico, messages=FALSE, echo=FALSE}
grafico_barras_felinos <-
felinos %>%
  ggplot(aes(x = species)) +
  geom_bar()

ggplotly(grafico_barras_felinos)
```
# Mapa
```{r mapa}
# Mapa leaflet básico de provincias y registros de presencia de felinos
leaflet() %>%
  addTiles() %>% # capa base de OSM
  addCircleMarkers( # capa de registros de presencia (puntos)
    data = felinos,
    stroke = F,
    radius = 4,
    fillColor = 'blue',
    fillOpacity = 1
  )

```




